produtos/urls.py
from django.urls import include, path
from .views import CategoriaListView, CategoriaCreateView, CategoriaUpdateView, CategoriaDeleteView, ProdutoListView, ProdutoCreateView, ProdutoUpdateView, ProdutoDeleteView


urlpatterns = [
    path('', include('movimentacao.urls')),
    # URLs para Categoria
    path('categorias/', CategoriaListView.as_view(), name='categoria_list'),
    path('categorias/nova/', CategoriaCreateView.as_view(), name='categoria_create'),
    path('categorias/<int:pk>/editar/', CategoriaUpdateView.as_view(), name='categoria_update'),
    path('categorias/<int:pk>/excluir/', CategoriaDeleteView.as_view(), name='categoria_delete'),

    # URLs para Produto
    path('', ProdutoListView.as_view(), name='produto_list'),
    path('produtos/novo/', ProdutoCreateView.as_view(), name='produto_create'),
    path('produtos/<int:pk>/editar/', ProdutoUpdateView.as_view(), name='produto_update'),
    path('produtos/<int:pk>/excluir/', ProdutoDeleteView.as_view(), name='produto_delete'),
]

setup/urls.py
from django.contrib import admin
from django.urls import include, path
from setup import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produtos.urls')),
    path('', include('movimentacao.urls')),
    path('', include('usuarios.urls')),
    path('', include('homepage.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movimentacao/models.py
from django.db import models
from produtos.models import Produto

class Movimentacao(models.Model):
    TIPO_MOVIMENTACAO =[
        ('E', 'Entrada'),
        ('S', 'Saida'),
    ]
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.IntegerField()
    data = models.DateField(auto_now_add=True)
    tipo = models.CharField(max_length=1, choices=TIPO_MOVIMENTACAO)
    valor_total = models.DecimalField(max_digits=10, decimal_places=2)

    def save(self, *args, **kwargs):
        self.valor_total = self.produto.preco * self.quantidade
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.produto} - {self.quantidade} unidades em {self.data} - valor total: {self.valor_total}"
    

produtos/models.py
from django.db import models

class Categoria(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

class Produto(models.Model):
    nome = models.CharField(max_length=100)
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    imagem = models.ImageField(upload_to='produtos/', null=True, blank=True)


    def __str__(self):
        return self.nome

produtos/forms.py
from django import forms
from produtos.models import Categoria, Produto

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nome']  
        labels = {
            'nome': 'Nome da Categoria',  
        }

class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ['nome', 'preco', 'categoria', 'imagem']
        labels = {
            'nome': 'Nome do Produto',
            'preco': 'Preço (R$)',
            'categoria': 'Categoria',
            'imagem': 'Imagem do Produto',
        }
        

produtos/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView


from produtos.forms import CategoriaForm, ProdutoForm
from .models import Produto, Categoria

# CBVs para Categoria
class CategoriaListView(ListView):
    model = Categoria
    template_name = 'categoria_list.html'

class CategoriaCreateView(CreateView):
    model = Categoria
    form_class = CategoriaForm
    template_name = 'categoria_form.html'
    success_url = reverse_lazy('categoria_list')

class CategoriaUpdateView(UpdateView):
    model = Categoria
    form_class = CategoriaForm
    template_name = 'categoria_form.html'
    success_url = reverse_lazy('categoria_list')

class CategoriaDeleteView(DeleteView):
    model = Categoria
    template_name = 'categoria_confirm_delete.html'
    success_url = reverse_lazy('categoria_list')

# CBVs para Produto
class ProdutoListView(ListView):
    model = Produto
    template_name = 'produto_list.html'

class ProdutoCreateView(CreateView):
    model = Produto
    form_class = ProdutoForm
    template_name = 'produto_form.html'
    success_url = reverse_lazy('produto_list')

class ProdutoUpdateView(UpdateView):
    model = Produto
    form_class = ProdutoForm
    template_name = 'produto_form.html'
    success_url = reverse_lazy('produto_list')

class ProdutoDeleteView(DeleteView):
    model = Produto
    template_name = 'produto_confirm_delete.html'
    success_url = reverse_lazy('produto_list')

produtos/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Projeto Modelo{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
</head>
<body>
    <header>
        <div class="esquerda">
            <img class="logo" src="{% static 'img/logo.png' %}" alt="">
            <a class="btn" href="{%url 'produto_list' %}">Produtos</a>
            <a class="btn" href="{%url 'categoria_list' %}">categoria</a>
            <a href="{% url "movimentacao_list" %}" class="btn">Movimentação</a>
        </div>

        <div class="direita" >
            <a href="" class="btn">home</a>
            <a href="{% url "profile" %}" class="btn">Perfil</a>
            <a href="{% url "logout" %}" class="btn">Logout</a>
            
        </div>
    </header>
    <div class="container">
        {% block content %}{% endblock%}
    </div>
    <footer>

    </footer>
</body>
</html>

produtos/templates/categoria_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Excluir Categoria{% endblock %}

{% block content %}
    <h2>Excluir Categoria</h2>

    <p>Tem certeza de que deseja excluir a categoria <strong>{{ object.nome }}</strong>?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirmar Exclusão</button>
        <a href="{% url 'categoria_list' %}">Cancelar</a>
    </form>
{% endblock %}

produtos/templates/categoria_form.html
{% extends 'base.html' %}

{% block title %}Formulário de Categoria{% endblock %}

{% block content %}
    <h2>{% if object %}Editar Categoria{% else %}Nova Categoria{% endif %}</h2>
   
    <form method="post" class="form-group">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">Salvar</button>
    </form>
   
    <a href="{% url 'categoria_list' %}" class="btn">Voltar para a lista de categorias</a>
{% endblock %}

produtos/templates/categoria_list.html
{% extends 'base.html' %}
{% block title %}Lista de Categorias{% endblock %}
{% block content %}
<h2>Lista de Categorias</h2>
<ul>
    {% for categoria in object_list %}
    <li>{{ categoria.nome }} - <a class="btn" href="{% url 'categoria_update' categoria.pk %}">Editar</a> - <a class = "btnv" href="{% url 'categoria_delete' categoria.pk %}">Excluir</a></li>
    {% endfor %}
</ul>
<a class = "btn" href="{% url 'categoria_create' %}">Nova Categoria</a>
{% endblock %}

produtos/templates/produto_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Excluir Produto{% endblock %}

{% block content %}
    <h2>Excluir Produto</h2>

    <p>Tem certeza de que deseja excluir o produto <strong>{{ object.nome }}</strong>?</p>
   
    <form method="post">
        {% csrf_token %}
        <button class = "btnv" type="submit">Confirmar Exclusão</button>
        <a class = "btn" href="{% url 'produto_list' %}">Cancelar</a>
    </form>
{% endblock %}

produtos/templates/produto_form.html
{% extends 'base.html' %}

{% block title %}{% if object %}Editar Produto{% else %}Novo Produto{% endif %}{% endblock %}

{% block content %}
    <h2>{% if object %}Editar Produto{% else %}Novo Produto{% endif %}</h2>
   
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class = "btn" type="submit">Salvar</button>
    </form>
   
    <a class = "btn" href="{% url 'produto_list' %}">Voltar para a lista de produtos</a>
{% endblock %}

produtos/templates/produto_list.html
{% extends 'base.html' %}

{% block title %}Lista de Produtos{% endblock %}

{% block content %}
    <h2>Lista de Produtos </h2>

    <table>
        <thead>
            <tr>
                <th>Nome</th>
                <th>Preço</th>
                <th>Categoria</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for produto in object_list %}
            <tr>
                <td>{{ produto.nome }}</td>
                <td>R$ {{ produto.preco }}</td>
                <td>{{ produto.categoria.nome }}</td>
                <td>
                    <a  href="{% url 'produto_update' produto.pk %}" class="btn">Editar</a>
                    <a href="{% url 'produto_delete' produto.pk %}" class="btnv">Excluir</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">Nenhum produto cadastrado.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <a class='btnv' href="{% url 'produto_create' %}">Novo Produto</a>
    <a class='btnv' href="{% url 'categoria_create' %}">Cadastrar Categoria</a>
{% endblock %}